services:
  - type: web
    name: django-porfolio
    runtime: python
    runtimeVersion: 3.11.0
    buildCommand: bash build.sh
    startCommand: gunicorn -c gunicorn_config.py django_porfolio.wsgi:application
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: SECRET_KEY
        scope: run
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: PYTHON_VERSION
        value: 3.10.5
