services:
  - type: web
    name: django-porfolio
    runtime: python
    runtimeVersion: 3.11.0
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: SECRET_KEY
        scope: run
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: orinchan.onrender.com,.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: PYTHON_VERSION
        value: 3.10.5
